import { PublicKey, SystemProgram, TransactionInstruction } from "@solana/web3.js";

export const PROGRAM_ID = new PublicKey(process.env.NEXT_PUBLIC_PROGRAM_ID ?? "HHkVyAqfGWvZrWuNqw1BwLqnr22Hbiwxp1exdoAxpzug");
const i64=(v:bigint)=>{const b=Buffer.alloc(8);b.writeBigInt64LE(v);return b};
const u64=(v:bigint)=>{const b=Buffer.alloc(8);b.writeBigUInt64LE(v);return b};
export function marketPda(authority:PublicKey,targetDay:bigint){return PublicKey.findProgramAddressSync([Buffer.from("market"),authority.toBuffer(),i64(targetDay)],PROGRAM_ID)}
export function vaultPda(market:PublicKey){return PublicKey.findProgramAddressSync([Buffer.from("vault"),market.toBuffer()],PROGRAM_ID)}
export function positionPda(market:PublicKey,user:PublicKey){return PublicKey.findProgramAddressSync([Buffer.from("position"),market.toBuffer(),user.toBuffer()],PROGRAM_ID)}
export function createMarketIx(authority:PublicKey,oracle:PublicKey,targetDay:bigint,closeTs:bigint,observationTs:bigint,thresholdUm:bigint){const [market]=marketPda(authority,targetDay);const [vault]=vaultPda(market);return new TransactionInstruction({programId:PROGRAM_ID,keys:[{pubkey:authority,isSigner:true,isWritable:true},{pubkey:market,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],data:Buffer.concat([Buffer.from([0]),i64(targetDay),i64(closeTs),i64(observationTs),u64(thresholdUm),oracle.toBuffer(),Buffer.from([0])])})}
export function betIx(user:PublicKey,market:PublicKey,side:0|1,lamports:bigint){const [position]=positionPda(market,user);const [vault]=vaultPda(market);return new TransactionInstruction({programId:PROGRAM_ID,keys:[{pubkey:user,isSigner:true,isWritable:true},{pubkey:market,isSigner:false,isWritable:true},{pubkey:position,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],data:Buffer.concat([Buffer.from([1,side]),u64(lamports)])})}
export function simpleIx(tag:number,keys:{pubkey:PublicKey,isSigner:boolean,isWritable:boolean}[],data=Buffer.alloc(0)){return new TransactionInstruction({programId:PROGRAM_ID,keys,data:Buffer.concat([Buffer.from([tag]),data])})}
export type Market={authority:PublicKey;oracle:PublicKey;targetDay:bigint;closeTs:bigint;observationTs:bigint;thresholdUm:bigint;yesPool:bigint;noPool:bigint;observedUm:bigint;settledAt:bigint;status:number;outcome:number};
export function decodeMarket(data:Buffer):Market{if(data.length!==160||data.subarray(0,8).toString()!=="WEATHER1")throw new Error("Invalid market account");return{authority:new PublicKey(data.subarray(8,40)),oracle:new PublicKey(data.subarray(40,72)),targetDay:data.readBigInt64LE(72),closeTs:data.readBigInt64LE(80),observationTs:data.readBigInt64LE(88),thresholdUm:data.readBigUInt64LE(96),yesPool:data.readBigUInt64LE(104),noPool:data.readBigUInt64LE(112),observedUm:data.readBigUInt64LE(120),settledAt:data.readBigInt64LE(128),status:data[136],outcome:data[137]}}
