"use client";
import {useCallback,useEffect,useState} from "react";import {useConnection,useWallet} from "@solana/wallet-adapter-react";import {WalletMultiButton} from "@solana/wallet-adapter-react-ui";import {CloudRain,ShieldCheck,ExternalLink,RefreshCw} from "lucide-react";import {LAMPORTS_PER_SOL,PublicKey,Transaction} from "@solana/web3.js";import {betIx,createMarketIx,decodeMarket,Market,marketPda,positionPda,PROGRAM_ID,simpleIx,vaultPda} from "@/lib/abi";
const short=(k:PublicKey)=>`${k.toBase58().slice(0,5)}…${k.toBase58().slice(-5)}`;const dt=(v:bigint)=>new Date(Number(v)*1000).toLocaleString();
export default function Home(){const {connection}=useConnection();const wallet=useWallet();const [address,setAddress]=useState("");const [market,setMarket]=useState<Market|null>(null);const [amount,setAmount]=useState("0.01");const [message,setMessage]=useState("Enter a market address to inspect live state.");const [busy,setBusy]=useState(false);const [date,setDate]=useState("");const [oracle,setOracle]=useState("");
const load=useCallback(async()=>{try{const key=new PublicKey(address);const info=await connection.getAccountInfo(key,"confirmed");if(!info)throw new Error("Market not found on Devnet");setMarket(decodeMarket(info.data));setMessage("Live state refreshed.")}catch(e){setMarket(null);setMessage(e instanceof Error?e.message:"Unable to load")}},[address,connection]);
useEffect(()=>{const q=new URLSearchParams(location.search).get("market");if(q)setAddress(q)},[]);
async function send(ix:ReturnType<typeof betIx>){if(!wallet.publicKey||!wallet.sendTransaction)throw new Error("Connect a wallet first");setBusy(true);try{const tx=new Transaction().add(ix);const sig=await wallet.sendTransaction(tx,connection);await connection.confirmTransaction(sig,"confirmed");setMessage(`Confirmed: ${sig}`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Transaction failed")}finally{setBusy(false)}}
async function bet(side:0|1){if(!wallet.publicKey||!market)return;const lamports=BigInt(Math.round(Number(amount)*LAMPORTS_PER_SOL));await send(betIx(wallet.publicKey,new PublicKey(address),side,lamports))}
async function close(){if(!wallet.publicKey)return;await send(simpleIx(2,[{pubkey:wallet.publicKey,isSigner:true,isWritable:false},{pubkey:new PublicKey(address),isSigner:false,isWritable:true}]))}
async function claim(refund=false){if(!wallet.publicKey)return;const m=new PublicKey(address);const [p]=positionPda(m,wallet.publicKey);const [v]=vaultPda(m);await send(simpleIx(refund?5:4,[{pubkey:wallet.publicKey,isSigner:true,isWritable:true},{pubkey:m,isSigner:false,isWritable:false},{pubkey:p,isSigner:false,isWritable:true},{pubkey:v,isSigner:false,isWritable:true}]))}
async function create(){if(!wallet.publicKey)return;const target=BigInt(Math.floor(new Date(`${date}T16:00:00Z`).getTime()/1000));setAddress(marketPda(wallet.publicKey,target)[0].toBase58());await send(createMarketIx(wallet.publicKey,new PublicKey(oracle||wallet.publicKey),target,target-86400n,target+28800n,100n))}
async function settle(){if(!wallet.publicKey||!market)return;const day=new Date(Number(market.targetDay)*1000).toISOString().slice(0,10);const w=await fetch(`/api/weather?date=${day}`).then(r=>r.json());if(typeof w.precipitationMm!=="number"){setMessage(w.error);return}const b=Buffer.alloc(16);b.writeBigInt64LE(BigInt(w.observedAt));b.writeBigUInt64LE(BigInt(Math.round(w.precipitationMm*1000)),8);await send(simpleIx(3,[{pubkey:wallet.publicKey,isSigner:true,isWritable:false},{pubkey:new PublicKey(address),isSigner:false,isWritable:true}],b))}
return <main><nav><a className="brand" href="#"><CloudRain size={24}/><span>Rain or Shine</span><b>DEVNET</b></a><WalletMultiButton/></nav><section className="hero"><div><p className="eyebrow">Shanghai · Open-Meteo daily precipitation</p><h1>Will it rain in Shanghai?</h1><p className="lede">A transparent two-sided prediction pool settled by an authorized weather oracle. Test SOL only.</p></div><div className="trust"><ShieldCheck/><div><strong>Trust model</strong><span>Oracle-authorized, not fully decentralized. Every settlement remains verifiable on-chain.</span></div></div></section><section className="lookup card"><label htmlFor="market">Market account</label><div className="row"><input id="market" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Paste a market PDA"/><button onClick={load} disabled={!address||busy}><RefreshCw size={18}/> Load live market</button></div><p role="status">{message}</p></section>{market&&<section className="grid"><article className="card market"><header><div><span className={`status s${market.status}`}>{["OPEN","CLOSED","SETTLED"][market.status]}</span><h2>{dt(market.targetDay)}</h2></div><a aria-label="View program in Solana Explorer" href={`https://explorer.solana.com/address/${PROGRAM_ID.toBase58()}?cluster=devnet`} target="_blank"><ExternalLink/></a></header><div className="pool"><div><span>YES pool</span><strong>{(Number(market.yesPool)/LAMPORTS_PER_SOL).toFixed(3)} SOL</strong></div><div><span>NO pool</span><strong>{(Number(market.noPool)/LAMPORTS_PER_SOL).toFixed(3)} SOL</strong></div></div><dl><div><dt>Betting closes</dt><dd>{dt(market.closeTs)}</dd></div><div><dt>Rain threshold</dt><dd>{Number(market.thresholdUm)/1000} mm</dd></div><div><dt>Oracle</dt><dd title={market.oracle.toBase58()}>{short(market.oracle)}</dd></div>{market.status===2&&<div><dt>Result</dt><dd>{market.outcome?"YES — rain":"NO — dry"} ({Number(market.observedUm)/1000} mm)</dd></div>}</dl></article><aside className="card actions"><h2>Trade & settle</h2><label htmlFor="amount">Amount (Devnet SOL)</label><input id="amount" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="choices"><button className="yes" disabled={busy||market.status!==0} onClick={()=>bet(1)}>Bet YES</button><button className="no" disabled={busy||market.status!==0} onClick={()=>bet(0)}>Bet NO</button></div><hr/><button className="secondary" disabled={busy} onClick={close}>Close market</button><button className="secondary" disabled={busy||market.status!==2} onClick={()=>claim(false)}>Claim winnings</button><button className="text" disabled={busy||market.status===2} onClick={()=>claim(true)}>Emergency refund</button></aside></section>}<footer><span>Demo for education · Devnet SOL has no monetary value</span><a href="https://open-meteo.com/en/docs" target="_blank">Weather source: Open-Meteo <ExternalLink size={14}/></a></footer></main>}
